# Generated by Django 6.1 on 2026-09-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('dosen', 'Dosen'), ('teman', 'Teman'), ('keluarga', 'Keluarga')], default='teman', max_length=20)),
            ],
        ),
    ]
