# Generated by Django 5.0.12 on 2026-09-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testimoni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
