# Generated by Django 5.0.12 on 2026-09-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_testimoni_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('fakultas', 'Fakultas'), ('eksternal', 'Eksternal'), ('kampus', 'Kampus')], default='fakultas', max_length=20)),
            ],
        ),
    ]
